import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { getServerSession } from 'next-auth'
import SessionProvider from '@/components/SessionProvider'
import Header from '@/components/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-full dark:bg-gray-950`}>
        <SessionProvider>
          <Header session={session} />
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
